main: com.owenselles.TimeCraft.Main
name: TimeCraft-Mention
version: 1.1
description: Main
author: VoxFall#6867
api-version: 1.13
commands:
  discord:
    description: Discord Command
  claimhelp:
    description: ClaimHelp Command
  ranks:
    description: Ranks Command
    aliases: [store, webstore]
  afk:
    description: Afk Command